"""Abstract base class for LLM conversation engines."""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional


class BaseLLMClient(ABC):
    """Abstract interface for LLM completion drivers."""

    @abstractmethod
    def generate_response(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ) -> str:
        """Generate conversational reply for the portrait.

        Args:
            user_message: Transcribed user speech.
            conversation_history: List of past turn dictionaries (e.g. [{'role': 'user', 'content': '...'}, ...]).
            system_prompt: Persona system instruction override.

        Returns:
            The generated in-character dialogue string.
        """
        pass

    def generate_response_stream(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ):
        """Yield text tokens as they are generated by the model.

        Default fallback yields the complete response as a single chunk.
        """
        reply = self.generate_response(user_message, conversation_history, system_prompt)
        if reply:
            yield reply

    def generate_clauses(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ):
        """Yield sentence/clause chunks suitable for immediate pipelined TTS synthesis."""
        buffer = ""
        for token in self.generate_response_stream(user_message, conversation_history, system_prompt):
            buffer += token

            # Full sentence endings split immediately
            split_found = False
            for mark in (". ", "! ", "? ", "\n"):
                if mark in buffer:
                    parts = buffer.split(mark, 1)
                    clause = (parts[0] + mark).strip()
                    if clause:
                        yield clause
                    buffer = parts[1]
                    split_found = True
                    break

            if split_found:
                continue

            # Comma splits only if accumulated part has at least 3 words
            if ", " in buffer:
                parts = buffer.split(", ", 1)
                first_part = parts[0].strip()
                if len(first_part.split()) >= 3:
                    clause = first_part + ","
                    yield clause
                    buffer = parts[1]
                    continue

            # Length-based chunking if no punctuation for 7+ words
            words = buffer.strip().split()
            if len(words) >= 7 and buffer.endswith(" "):
                clause = buffer.strip()
                if clause:
                    yield clause
                buffer = ""

        remainder = buffer.strip()
        if remainder:
            yield remainder
