"""Abstract base class for LLM conversation engines."""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from llm.streaming import speech_clauses


class BaseLLMClient(ABC):
    """Abstract interface for LLM completion drivers."""

    @abstractmethod
    def generate_response(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ) -> str:
        """Generate conversational reply for the portrait.

        Args:
            user_message: Transcribed user speech.
            conversation_history: List of past turn dictionaries (e.g. [{'role': 'user', 'content': '...'}, ...]).
            system_prompt: Persona system instruction override.

        Returns:
            The generated in-character dialogue string.
        """
        pass

    def generate_response_stream(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ):
        """Yield text tokens as they are generated by the model.

        Default fallback yields the complete response as a single chunk.
        """
        reply = self.generate_response(user_message, conversation_history, system_prompt)
        if reply:
            yield reply

    def generate_clauses(
        self,
        user_message: str,
        conversation_history: Optional[List[Dict[str, str]]] = None,
        system_prompt: Optional[str] = None,
    ):
        """Yield sentence/clause chunks suitable for immediate pipelined TTS synthesis."""
        yield from speech_clauses(
            self.generate_response_stream(user_message, conversation_history, system_prompt)
        )
